{% set version = "3.4.37" %}

package:
  name: mcxtrace-suite
  version: {{ version }}

# sha256 value manually found by
# curl -sL url | openssl sha256
source:
  url: https://github.com/McStasMcXtrace/McCode/archive/mcxtrace-{{ version }}.tar.gz
  sha256: 6be369b216578c64b8ac66468f3bc0eb783bd0a37e7c71df7723a0b66660c785
  folder: src

build:
  number: 0

outputs:

  - name: mcxtrace-core
    script: install-files-core.sh  # [unix]
    script: install-files-core.bat  # [win]
    requirements:
      build:
        - cmake
        - make  # [unix]
        - {{ compiler('c') }}
        - flex  # [unix]
        - bison  # [unix]
        - winflexbison  # [win]
        - mslex  # [win]
        - msmpi  # [win]
        - openmpi  # [not win]
      host:
        - dirent  # [win]
      run:
        - python
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - bash  # [unix]
        # for mxrun
        - pyaml
        # for traces from mxrun
        - ply
        - mslex  # [win]
        - msmpi  # [win]
        - openmpi  # [not win]
        - nexus  # [not (aarch64 or ppc64le)]
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py core
      source_files:
        - src/mcxtrace-comps/examples/ESRF/ESRF_BM29/ESRF_BM29.instr
        - src/mcxtrace-comps/examples/AstroX_ESA/NuSTAR_1shell_con/NuSTAR_1shell_con.instr

  - name: mcxtrace-data
    build:
      noarch: generic
    script: install-files-data.sh  # [unix]
    script: install-files-data.bat  # [win]
    test:
      files:
        - test_pkg.py
      requires:
        - python
      commands:
        - python test_pkg.py data

  - name: mcxtrace-mxgui
    requirements:
      run:
        - mcxtrace-core
        - pyqt
        - qscintilla2
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py mxgui

  - name: mcxtrace-vis
    requirements:
      run:
        - mcxtrace-core
        #  Note: conda-forge linter wants matplotlib-base and not matplotlib. It
        #  actually makes no difference (as per October 2023) since we anyway
        #  install tornado+pyqt.
        - matplotlib-base
        - numpy
        - tornado >=5
        - scipy
        - pillow
        - pyqtgraph
        - pyqt >=5.10
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py vis

  - name: mcxtrace
    test:
      files:
        - test_pkg.py
      requires:
      commands:
        - python test_pkg.py mcxtrace
    requirements:
      run:
        - {{ pin_subpackage('mcxtrace-core', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcxtrace-data', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcxtrace-mxgui', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcxtrace-vis', max_pin="x.x.x") }}
        - mcpl  # [unix and not (aarch64 or ppc64le)]

about:
  home: https://mcxtrace.org/
  summary: McXtrace is a general tool for simulating x-ray scattering instruments and experiments.
  description: |
    McXtrace is a general tool for simulating x-ray scattering instruments and
    experiments.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: src/COPYING
  doc_url: https://mcxtrace.org/
  dev_url: https://github.com/McStasMcXtrace/McCode

extra:
  recipe-maintainers:
    - willend
    - tkittel
    - ebknudsen
