{% set version = "3.5.6" %}

package:
  name: mcxtrace-suite
  version: {{ version }}

# sha256 value manually found by
# curl -sL url | openssl sha256
source:
  url: https://github.com/McStasMcXtrace/McCode/archive/v{{ version }}.tar.gz
  sha256: 5894bbd0840d106bf227a9a23ed9fb7dbe20356d0b474bfb2aac8fe0add90b04
  folder: src

build:
  number: 0

outputs:

  - name: mcxtrace-core
    script: install-files-core.sh  # [unix]
    script: install-files-core.bat  # [win]
    requirements:
      build:
        - cmake
        - make  # [unix]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - flex  # [unix]
        - bison  # [unix]
        - winflexbison  # [win]
        - mslex  # [win]
        - nodejs
        - msmpi  # [win]
        - openmpi=4  # [unix]
      host:
        - dirent  # [win]
      run:
        - python
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - bash  # [unix]
        # for mxrun
        - pyaml
        # for traces from mxrun
        - ply
        - mslex  # [win]
        # for sync of 3D / js files
        - rsync  # [unix]
        - mcstasscript
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py core
      source_files:
        - src/mcxtrace-comps/examples/ESRF/ESRF_BM29/ESRF_BM29.instr
        - src/mcxtrace-comps/examples/AstroX_ESA/NuSTAR_1shell_con/NuSTAR_1shell_con.instr

  - name: mcxtrace-data
    build:
      noarch: generic
    script: install-files-data.sh  # [unix]
    script: install-files-data.bat  # [win]
    test:
      files:
        - test_pkg.py
      requires:
        - python
      commands:
        - python test_pkg.py data

  - name: mcxtrace-mxgui
    requirements:
      run:
        - mcxtrace-core
        - pyqt
        - qscintilla2
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py mxgui

  - name: mcxtrace-vis
    requirements:
      run:
        - mcxtrace-core
        #  Note: conda-forge linter wants matplotlib-base and not matplotlib. It
        #  actually makes no difference (as per October 2023) since we anyway
        #  install tornado+pyqt.
        - matplotlib-base
        - numpy
        - tornado >=5
        - scipy
        - pillow
        - pyqtgraph
        - pyqt >=5.10
        - nodejs
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py vis

  - name: mcxtrace
    test:
      files:
        - test_pkg.py
      requires:
      commands:
        - python test_pkg.py mcxtrace
    requirements:
      run:
        - {{ pin_subpackage('mcxtrace-core', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcxtrace-data', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcxtrace-mxgui', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcxtrace-vis', max_pin="x.x.x") }}
        - msmpi  # [win]
        - openmpi=4  # [unix]
        - gsl
        - xraylib
        - libnexus
        - nexpy
        - mcpl  # [unix]

about:
  home: https://mcxtrace.org/
  summary: McXtrace is a general tool for simulating x-ray scattering instruments and experiments.
  description: |
    McXtrace is a general tool for simulating x-ray scattering instruments and
    experiments.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: src/COPYING
  doc_url: https://mcxtrace.org/
  dev_url: https://github.com/McStasMcXtrace/McCode

extra:
  recipe-maintainers:
    - willend
    - tkittel
    - ebknudsen
